### ISSUE TITLE
licence

### ISSUE THREAD

**Issue by MrYogi** [Pi-Developers/Pi-Locker#10]
what is licence of  PI locker code? is it available for personal and commercial use?

**Comment by MohammedRashad** [comment]
GNU Public License,  
yes, but with posting our code as open source fork

**Comment by filipst** [comment]
Please tell me how do I post your code as open source fork?

**Comment by MohammedRashad** [comment]
you can fork it with respect to GNU public license you can read here
https://github.com/Pi-Developers/Pi-Locker/blob/master/LICENSE
